### ISSUE TITLE
Usage of the private key is not valid

### ISSUE THREAD

**Issue by aboimpinto** [jnlewis/neo-dapp-tutorial#3]
Hello, 

I'm trying to use the code in this tutorial to connect to the PrivateNet. In the Blockchain.cs I add the private key (WIF) if the wallet and when I try to execute or query the blockchain I get error in the line

![image](https://user-images.githubusercontent.com/1231687/47960432-42301480-dffc-11e8-9f88-832e99e88830.png)

doing the HexToBytes conversion.

what I'm doing wrong?

tkx
Paulo

**Comment by jnlewis** [comment]
Hi Paulo,

Just to confirm, is your private key in Hex format? If it is then the HexToBytes should work. Otherwise, can you try removing the reference to Neo.Lux and then re-adding it from the NuGet package manager. I tested on Neo.Lux version 0.8.0.

**Comment by aboimpinto** [comment]
Yes .. found this later. In the docmentation please refer that and will solve several hours of the developer

tkx for the answer

**Comment by jnlewis** [comment]
noted! thanks for the feedback. The docs was not clear on this, sorry for the inconvenience.

**Comment by aboimpinto** [comment]
no problem man!! we are here to find errors and telling you that everything is ok!! ;)

keep up the good wotk
